/*
    Tests generated by ChatGPT
 */
package repoTest;

import db.Db;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import repo.AccountRepo;

import java.nio.file.Path;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AccountRepoTest {

    // AI GENERATED CODE
    @TempDir
    Path tempDir;

    private Db db;
    private AccountRepo accountRepo;

    // Runs before each test, ensures a clean database state
    // Isolates accounts table for testing
    @BeforeEach
    void setUp() throws Exception {
        db = new Db(tempDir, "account-test.db");
        accountRepo = new AccountRepo(db);

        // Use a fresh table in the database to ensure tests don't interfere with each other
        try (Connection c = db.connect(); Statement stmt = c.createStatement()) {
            // Drop the table if it exists to start clean
            stmt.execute("DROP TABLE IF EXISTS accounts");

            // Create the accounts table with the same structure as production,
            stmt.execute("""
                    CREATE TABLE accounts(
                        accID VARCHAR(50) PRIMARY KEY,  --account ID is unique
                        accName VARCHAR(100),           --name of the account
                        accType VARCHAR(50),            --type of account (e.g., Checking, Savings)
                        currency VARCHAR(10)            --currency code (e.g., USD, EUR)
                    )
                    """);
        }
    }

    // Test inserting a single account
    @Test
    void testInsertAccountRecord() {
        // Insert one account into the table
        accountRepo.insertAccountRecord("001", "Main Account", "Checking", "USD");

        // Retrieve the list of accounts as strings
        List<String> accounts = accountRepo.accListToString();

        // Check that there is exactly one account in the table
        assertEquals(1, accounts.size());

        // Check that the output string matches the expected format
        assertEquals("001: Main Account: Checking (USD)", accounts.get(0));
    }

    // Test inserting multiple accounts and check ordering
    @Test
    void testAccListToStringMultipleRecords() {
        // Insert three accounts
        accountRepo.insertAccountRecord("001", "Main Account", "Checking", "USD");
        accountRepo.insertAccountRecord("002", "Savings", "Savings", "EUR");
        accountRepo.insertAccountRecord("003", "Invest", "Investment", "GBP");

        // Retrieve all accounts
        List<String> accounts = accountRepo.accListToString();

        // Verify that all three records exist
        assertEquals(3, accounts.size());

        // Check that the ordering by accID is correct
        assertEquals("001: Main Account: Checking (USD)", accounts.get(0));
        assertEquals("002: Savings: Savings (EUR)", accounts.get(1));
        assertEquals("003: Invest: Investment (GBP)", accounts.get(2));
    }

    // Test behavior when inserting a duplicate accID (primary key violation)
    @Test
    void testInsertDuplicateAccIDThrows() {
        // Insert one account
        accountRepo.insertAccountRecord("001", "Main Account", "Checking", "USD");

        // Attempting to insert another account with the same accID should throw RuntimeException
        RuntimeException exception = assertThrows(RuntimeException.class, () ->
                accountRepo.insertAccountRecord("001", "Duplicate", "Checking", "USD")
        );

        // Check that the underlying cause is an SQL exception (constraint violation)
        assertTrue(exception.getCause() instanceof java.sql.SQLException);
    }

    // Test that accListToString() returns an empty list when table has no records
    @Test
    void testEmptyTableReturnsEmptyList() {
        // Retrieve accounts from an empty table
        List<String> accounts = accountRepo.accListToString();

        // The list should be empty
        assertTrue(accounts.isEmpty());
    }
}
